services:
   redis:
      image: redis:7-alpine
      restart: always
      env_file: .env
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:${REDIS_DATA}
      command: [ "--requirepass", "${REDIS_PASSWORD}" ]

   postgres:
      image: postgres:16-alpine
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

   pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4:7
      restart: always
      environment:
         PGADMIN_DEFAULT_EMAIL: admin@admin.com
         PGADMIN_DEFAULT_PASSWORD: root
      ports:
         - "5050:80"
      volumes:
         - pgadmin-data:/var/lib/pgadmin

   bot:
      build: .
      restart: always
      env_file: .env
      depends_on:
         - redis
         - postgres
      ports:
         - "${SERVER_PORT}:${SERVER_PORT}"
      entrypoint: [ "/app/scripts/run-bot.sh" ]

volumes:
   redis-data:
   postgres-data:
   pgadmin-data: